vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: '%product_attachements%'
            upload_destination: '%kernel.project_dir%/public%product_attachements%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: false
            delete_on_update: false
